In [1]:
import numpy as np
import pandas as pd

In [2]:
individual_record = '../bdhs-dataset/BDIR81SV/BDIR81FL.csv'
personal_record = '../bdhs-dataset/BDPR81SV/BDPR81FL.csv'

df_ind = pd.read_csv(individual_record)
df_psn = pd.read_csv(personal_record)
display(df_ind.head())
display(df_psn.head())

/tmp/ipykernel_54381/2398667696.py:4: DtypeWarning: Columns (0: V160, 1: VCAL$2, 2: S113A, 3: S115) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ind = pd.read_csv(individual_record)
/tmp/ipykernel_54381/2398667696.py:5: DtypeWarning: Columns (0: HV225, 1: HV230B, 2: HV232, 3: HV232B, 4: HV232Y, 5: HV235, 6: HV238A, 7: SH151A) have mixed types. Specify dtype option on import or set low_memory=False.
  df_psn = pd.read_csv(personal_record)

,CASEID,V000,V001,V002,V003,V004,V005,V006,V007,V008,...,S631J$3,S631J$4,S631J$5,S631J$6,S631K$1,S631K$2,S631K$3,S631K$4,S631K$5,S631K$6
0,1 1 3,BD8,1,1,3,1,156207,9,2022,1473,...,,,,,,,,,,
1,1 4 2,BD8,1,4,2,1,156207,9,2022,1473,...,,,,,,,,,,
2,1 7 3,BD8,1,7,3,1,156207,9,2022,1473,...,,,,,,,,,,
3,1 10 2,BD8,1,10,2,1,156207,9,2022,1473,...,,,,,,,,,,
4,1 13 2,BD8,1,13,2,1,156207,9,2022,1473,...,,,,,,,,,,

,HHID,HVIDX,HV000,HV001,HV002,HV003,HV004,HV005,HV006,HV007,...,SB362C,SB363A,SB363B,SB363C,SB366D,SB366M,SB366Y,SB366T,SB367,SB367G
0,1 1,1,BD8,1,1,3,1,155639,9,2022,...,,,,,,,,,,
1,1 1,2,BD8,1,1,3,1,155639,9,2022,...,,1,,,14,9,2022,612,74,4.6
2,1 1,3,BD8,1,1,3,1,155639,9,2022,...,,,,,,,,,,
3,1 1,4,BD8,1,1,3,1,155639,9,2022,...,,,,,,,,,,
4,1 4,1,BD8,1,4,2,1,155639,9,2022,...,,,,,,,,,,

In [3]:
df_merged = df_ind.merge(
    df_psn,
    left_on=["V001", "V002", "V003"],
    right_on=["HV001", "HV002", "HVIDX"],
    how="left",
    validate="one_to_one"
)
df_merged.head()

,CASEID,V000,V001,V002,V003,V004,V005,V006,V007,V008,...,SB362C,SB363A,SB363B,SB363C,SB366D,SB366M,SB366Y,SB366T,SB367,SB367G
0,1 1 3,BD8,1,1,3,1,156207,9,2022,1473,...,,,,,,,,,,
1,1 4 2,BD8,1,4,2,1,156207,9,2022,1473,...,,,,,,,,,,
2,1 7 3,BD8,1,7,3,1,156207,9,2022,1473,...,,,,,,,,,,
3,1 10 2,BD8,1,10,2,1,156207,9,2022,1473,...,,,,,,,,,,
4,1 13 2,BD8,1,13,2,1,156207,9,2022,1473,...,,,,,,,,,,

In [4]:
df_merged.shape

(30078, 5974)

In [5]:
# Population
evermarried_cols = ['V020', 'S111A', 'V501']
gender_cols = ['HV104']

# Combine
population_cols = evermarried_cols + gender_cols

In [6]:
# Cardio-metabolic burder
diabetes_cols = ['SB267', 'SB236', 'SB240']
hypertension_cols = ['WBP24', 'WBP25', 'WBP16', 'WBP19']
obesity_cols = ['HA40']

# Anxiety / Depression
depression_cols = ['MTH22']
anxiety_cols = ['MTH24']

# Socio-economic Status
education_cols = ['V133', 'V149', 'V106']
wealth_cols = ['V190', 'V190A', 'V191', 'V191A']
occupation_cols = ['V714', 'V731', 'V716', 'V717', 'V704', 'V705']

# Combine
exposure_cols = diabetes_cols + hypertension_cols + obesity_cols + depression_cols + anxiety_cols + education_cols + wealth_cols + occupation_cols

In [7]:
# Confounders
age_cols = ['V012', 'V013']
residence_cols = ['V024', 'V025', 'V026']
marrage_cols = ['V511', 'V511A', 'V513']
religion_cols = ['V130']
children_cols = ['V201', 'V212', 'V218', 'V219']
household_cols = ['V136', 'V137', 'V138']
sleep_cols = ['MTH10']
selfhealth_cols = ['V176']
insurance_cols = ['V481']
media_cols = ['V157', 'V158', 'V159', 'V171A']
alcohol_coils = ['V485A', 'V485B']
contraceptive_cols = ['V312', 'V313']
abortion_cols = ['V228']

decision_cols = [f'V743{i}' for i in 'ABCDEF']
abuse_cols = [f'V744{i}' for i in 'ABCDE']

smoking_cols = [f'V463{i}' for i in 'ABCDEFGHIJKLXZ']
smoking_cols += ['V463AA', 'V463AB', 'V464']

food_cols = [f'V471{i}' for i in 'ABCDEFGHI'] + ['V471CS']
food_cols += [f'V472{i}' for i in 'ABCDEFGHIJKLMNOPQRSTUVW']
food_cols += [f'V472W{i}' for i in 'ABCDE']

# Combine
confounders_cols = age_cols + residence_cols + marrage_cols + religion_cols + children_cols + household_cols + sleep_cols + selfhealth_cols + insurance_cols + media_cols + alcohol_coils + contraceptive_cols + abortion_cols + decision_cols + abuse_cols + smoking_cols + food_cols

In [8]:
# All Columns
cols = population_cols + exposure_cols + confounders_cols
len(cols)

121

In [9]:
df = df_merged[cols]
df.head()

,V020,S111A,V501,HV104,SB267,SB236,SB240,WBP24,WBP25,WBP16,...,V472S,V472T,V472U,V472V,V472W,V472WA,V472WB,V472WC,V472WD,V472WE
0,1,1,1,2,139,0,,129,97,1,...,,,,,,,,,,
1,1,1,1,2,,,,,,,...,,,,,,,,,,
2,1,1,1,2,,,,,,,...,,,,,,,,,,
3,1,1,1,2,,,,,,,...,,,,,,,,,,
4,1,1,1,2,,,,,,,...,,,,,,,,,,

In [10]:
df.replace(r'^\s*$', np.nan, regex=True, inplace=True)
df.head()

,V020,S111A,V501,HV104,SB267,SB236,SB240,WBP24,WBP25,WBP16,...,V472S,V472T,V472U,V472V,V472W,V472WA,V472WB,V472WC,V472WD,V472WE
0,1,1,1,2,139,0,NaN,129,97,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,1,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1,1,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1,1,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,1,1,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Features not found in BDHS dataset
df.loc[:, df.isna().sum() == df.shape[0]].columns

Index(['V511A', 'V176', 'V485A', 'V485B', 'V743C', 'V743E', 'V463A', 'V463B',
       'V463C', 'V463D', 'V463E', 'V463F', 'V463G', 'V463H', 'V463I', 'V463J',
       'V463K', 'V463L', 'V463X', 'V463Z', 'V463AA', 'V463AB', 'V464', 'V471A',
       'V471B', 'V471C', 'V471D', 'V471E', 'V471F', 'V471G', 'V471H', 'V471I',
       'V471CS', 'V472A', 'V472B', 'V472C', 'V472D', 'V472E', 'V472F', 'V472G',
       'V472H', 'V472I', 'V472J', 'V472K', 'V472L', 'V472M', 'V472N', 'V472O',
       'V472P', 'V472Q', 'V472R', 'V472S', 'V472T', 'V472U', 'V472V', 'V472W',
       'V472WA', 'V472WB', 'V472WC', 'V472WD', 'V472WE'],
      dtype='str')

In [12]:
# Removing "All NaN" columns and rows
df = df.loc[:, df.isna().sum() != df.shape[0]]
df = df.loc[df.isna().sum(axis=1) != df.shape[1], :]
df.head()

,V020,S111A,V501,HV104,SB267,SB236,SB240,WBP24,WBP25,WBP16,...,V228,V743A,V743B,V743D,V743F,V744A,V744B,V744C,V744D,V744E
0,1,1,1,2,139,0,NaN,129,97,1,...,1,2,2,2,2,0,0,0,0,0
1,1,1,1,2,NaN,NaN,NaN,NaN,NaN,NaN,...,0,1,2,1,7,0,0,0,0,0
2,1,1,1,2,NaN,NaN,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1,1,2,NaN,NaN,NaN,NaN,NaN,NaN,...,0,2,2,2,2,0,0,0,0,0
4,1,1,1,2,NaN,NaN,NaN,NaN,NaN,NaN,...,1,2,4,2,2,0,0,0,0,0

In [13]:
df.shape

(30078, 60)

In [14]:
df.to_csv('../bdhs-dataset/dataset.csv', index=False)