In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_depression = pd.read_csv('../resources/depression_dataset.csv')
df_anxiety = pd.read_csv('../resources/anxiety_dataset.csv')
display(df_depression.head())
display(df_anxiety.head())

,Cardiometabolic Burden,Socioeconomic Status,Depression,Education,Occupation,Partner occupation,Age,Division,Residence,Religion,...,Contraceptive,Abortion,Pregnant,Menopause,Sexual activity,Postpartum,CASEID,Sampling weight,PSU,Stratum
0,3,5,1,3,0.0,1,3,1,1,1,...,0.0,1,0,0,0,0,1 1 3,0.156207,1,1
1,0,4,1,0,1.0,2,3,1,1,2,...,2.0,0,0,0,1,0,1 18 2,0.156207,1,1
2,0,4,0,2,1.0,2,1,1,1,1,...,0.0,0,1,0,1,0,1 35 2,0.156207,1,1
3,0,4,0,2,0.0,2,2,1,1,2,...,0.0,0,0,0,1,0,1 52 2,0.156207,1,1
4,0,5,0,2,0.0,2,3,1,1,2,...,0.0,1,0,0,0,0,1 69 2,0.156207,1,1

,Cardiometabolic Burden,Socioeconomic Status,Anxiety,Education,Occupation,Partner occupation,Age,Division,Residence,Religion,...,Contraceptive,Abortion,Pregnant,Menopause,Sexual activity,Postpartum,CASEID,Sampling weight,PSU,Stratum
0,3,5,1,3,0.0,1,3,1,1,1,...,0.0,1,0,0,0,0,1 1 3,0.156207,1,1
1,0,4,1,0,1.0,2,3,1,1,2,...,2.0,0,0,0,1,0,1 18 2,0.156207,1,1
2,0,4,0,2,1.0,2,1,1,1,1,...,0.0,0,1,0,1,0,1 35 2,0.156207,1,1
3,0,4,0,2,0.0,2,2,1,1,2,...,0.0,0,0,0,1,0,1 52 2,0.156207,1,1
4,0,5,0,2,0.0,2,3,1,1,2,...,0.0,1,0,0,0,0,1 69 2,0.156207,1,1

In [3]:
display(df_anxiety.shape)
display(df_depression.shape)

(4887, 27)

(4887, 27)

In [4]:
from tools.recode import recode, clean_recode, parse_recode, investigate_row

In [5]:
def parse(var: str) -> None:
    """
    Details of a variable (displayed simply)
    """
    var_dict = recode.get(var, None) or clean_recode.get(var, None)
    if not var_dict:
        print("Variable not found in the recode list!")
        return None

    print(f"Name: {var_dict['name']}")
    value = var_dict.get("value", None)
    if value is None:
        print("Value: Continuous variable")
        return None
    print(f"Categories: ")
    for i, j in value.items():
        print(f"\t{i}: {j}")

## Missing Values

In [6]:
df_depression.isna().sum(axis=0)

Cardiometabolic Burden       0
Socioeconomic Status         0
Depression                   0
Education                    0
Occupation                   0
Partner occupation           0
Age                          0
Division                     0
Residence                    0
Religion                     0
Children                     0
Family size                  0
Household Autonomy           0
Financial Decision-Making    0
IPV Attitude                 0
Insurance                    0
Internet                     0
Contraceptive                0
Abortion                     0
Pregnant                     0
Menopause                    0
Sexual activity              0
Postpartum                   0
CASEID                       0
Sampling weight              0
PSU                          0
Stratum                      0
dtype: int64

In [7]:
df_anxiety.isna().sum(axis=0)

Cardiometabolic Burden       0
Socioeconomic Status         0
Anxiety                      0
Education                    0
Occupation                   0
Partner occupation           0
Age                          0
Division                     0
Residence                    0
Religion                     0
Children                     0
Family size                  0
Household Autonomy           0
Financial Decision-Making    0
IPV Attitude                 0
Insurance                    0
Internet                     0
Contraceptive                0
Abortion                     0
Pregnant                     0
Menopause                    0
Sexual activity              0
Postpartum                   0
CASEID                       0
Sampling weight              0
PSU                          0
Stratum                      0
dtype: int64