In [31]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [32]:
df_depression = pd.read_csv('../resources/depression_dataset.csv')
df_anxiety = pd.read_csv('../resources/anxiety_dataset.csv')
display(df_depression.head())
display(df_anxiety.head())

,Cardiometabolic Burden,Socioeconomic Status,Depression,Marital status,Education,Occupation,Partner occupation,Age,Division,Residence,...,Abortion,Pregnant,Menopause,Sexual activity,Postpartum,CASEID,Cluster number,Sampling weight,PSU,Stratum
0,3,5,1,1,3,0.0,1.0,3,1,1,...,1,0,0,0,0,1 1 3,1,0.156207,1,1
1,0,4,1,1,0,1.0,2.0,3,1,1,...,0,0,0,1,0,1 18 2,1,0.156207,1,1
2,0,4,0,1,2,1.0,2.0,1,1,1,...,0,1,0,1,0,1 35 2,1,0.156207,1,1
3,0,4,0,1,2,0.0,2.0,2,1,1,...,0,0,0,1,0,1 52 2,1,0.156207,1,1
4,1,5,0,1,2,0.0,2.0,3,1,1,...,1,0,0,0,0,1 69 2,1,0.156207,1,1

,Cardiometabolic Burden,Socioeconomic Status,Anxiety,Marital status,Education,Occupation,Partner occupation,Age,Division,Residence,...,Abortion,Pregnant,Menopause,Sexual activity,Postpartum,CASEID,Cluster number,Sampling weight,PSU,Stratum
0,3,5,1,1,3,0.0,1.0,3,1,1,...,1,0,0,0,0,1 1 3,1,0.156207,1,1
1,0,4,1,1,0,1.0,2.0,3,1,1,...,0,0,0,1,0,1 18 2,1,0.156207,1,1
2,0,4,0,1,2,1.0,2.0,1,1,1,...,0,1,0,1,0,1 35 2,1,0.156207,1,1
3,0,4,0,1,2,0.0,2.0,2,1,1,...,0,0,0,1,0,1 52 2,1,0.156207,1,1
4,1,5,0,1,2,0.0,2.0,3,1,1,...,1,0,0,0,0,1 69 2,1,0.156207,1,1

In [33]:
display(df_anxiety.shape)
display(df_depression.shape)

(5137, 28)

(5137, 28)

In [34]:
from tools.recode import recode, clean_recode, parse_recode, investigate_row

In [35]:
def parse(var: str) -> None:
    """
    Details of a variable (displayed simply)
    """
    var_dict = recode.get(var, None) or clean_recode.get(var, None)
    if not var_dict:
        print("Variable not found in the recode list!")
        return None

    print(f"Name: {var_dict['name']}")
    value = var_dict.get("value", None)
    if value is None:
        print("Value: Continuous variable")
        return None
    print(f"Categories: ")
    for i, j in value.items():
        print(f"\t{i}: {j}")

## Missing Values

In [36]:
df_depression.isna().sum(axis=0)

Cardiometabolic Burden    0
Socioeconomic Status      0
Depression                0
Marital status            0
Education                 0
Occupation                0
Partner occupation        8
Age                       0
Division                  0
Residence                 0
Religion                  1
Children                  0
Family size               0
Autonomy                  0
Abuse                     0
Insurance                 0
Internet                  0
Contraceptive             0
Abortion                  0
Pregnant                  0
Menopause                 0
Sexual activity           0
Postpartum                0
CASEID                    0
Cluster number            0
Sampling weight           0
PSU                       0
Stratum                   0
dtype: int64

In [37]:
df_anxiety.isna().sum(axis=0)

Cardiometabolic Burden    0
Socioeconomic Status      0
Anxiety                   0
Marital status            0
Education                 0
Occupation                0
Partner occupation        8
Age                       0
Division                  0
Residence                 0
Religion                  1
Children                  0
Family size               0
Autonomy                  0
Abuse                     0
Insurance                 0
Internet                  0
Contraceptive             0
Abortion                  0
Pregnant                  0
Menopause                 0
Sexual activity           0
Postpartum                0
CASEID                    0
Cluster number            0
Sampling weight           0
PSU                       0
Stratum                   0
dtype: int64

## Investigate missing data

#### Missing Religion

In [38]:
df_depression[df_depression["Religion"].isna()]

,Cardiometabolic Burden,Socioeconomic Status,Depression,Marital status,Education,Occupation,Partner occupation,Age,Division,Residence,...,Abortion,Pregnant,Menopause,Sexual activity,Postpartum,CASEID,Cluster number,Sampling weight,PSU,Stratum
4022,2,2,0,1,2,1.0,2.0,3,7,1,...,1,0,1,0,0,532 2 2,532,0.552507,532,13

In [39]:
investigate_row(df_depression[df_depression["Religion"].isna()].iloc[0])

Cardiometabolic Burden           Two burden
Socioeconomic Status                 Poorer
Depression                    0-4 (minimal)
Marital status            Currently married
Education                         Secondary
Occupation                              Yes
Partner occupation                  Working
Age                                   35-49
Division                            Rangpur
Residence                             Urban
Religion                                NaN
Children                                  3
Family size                     Less than 5
Autonomy                        4 dicisions
Abuse                                    No
Insurance                                No
Internet                              Never
Contraceptive                     No method
Abortion                                Yes
Pregnant                       No or unsure
Menopause                               Yes
Sexual activity                  Not Active
Postpartum                               No
CASEID                           532   2  2
Cluster number                          532
Sampling weight                    0.552507
PSU                                     532
Stratum                                  13
Name: 4022, dtype: object

#### Missing Partner occupation

In [40]:
df_depression[df_depression["Partner occupation"].isna()]

,Cardiometabolic Burden,Socioeconomic Status,Depression,Marital status,Education,Occupation,Partner occupation,Age,Division,Residence,...,Abortion,Pregnant,Menopause,Sexual activity,Postpartum,CASEID,Cluster number,Sampling weight,PSU,Stratum
311,0,3,0,1,2,0.0,NaN,2,1,2,...,0,0,0,0,0,42 1 5,42,0.790094,42,2
1255,0,5,0,1,3,0.0,NaN,1,2,2,...,0,0,0,1,0,156 1 4,156,1.616444,156,4
1409,2,5,0,1,0,0.0,NaN,3,3,1,...,0,0,0,0,0,174 114 5,174,1.176988,174,5
1751,2,5,1,1,0,0.0,NaN,3,3,2,...,0,0,0,0,0,224 43 1,224,1.449553,224,6
1752,0,5,1,1,3,0.0,NaN,1,3,2,...,0,0,0,0,0,224 43 2,224,1.449553,224,6
2245,0,5,0,1,3,0.0,NaN,2,4,1,...,0,0,0,1,0,293 65 3,293,0.782882,293,7
3926,0,1,1,1,1,0.0,NaN,1,6,2,...,0,0,0,0,1,517 116 3,517,1.287810,517,12
3999,0,4,0,1,1,0.0,NaN,1,7,1,...,0,0,0,0,0,528 93 3,528,0.507989,528,13

In [41]:
for i in range(8):
    display(investigate_row(df_depression[df_depression["Partner occupation"].isna()].iloc[i]))

Cardiometabolic Burden                 None
Socioeconomic Status                 Middle
Depression                    0-4 (minimal)
Marital status            Currently married
Education                         Secondary
Occupation                               No
Partner occupation                      NaN
Age                                   25-34
Division                           Barishal
Residence                             Rural
Religion                              Islam
Children                                  2
Family size                       5 or more
Autonomy                        4 dicisions
Abuse                                    No
Insurance                                No
Internet                                Yes
Contraceptive                     No method
Abortion                                 No
Pregnant                       No or unsure
Menopause                                No
Sexual activity                  Not Active
Postpartum                               No
CASEID                            42   1  5
Cluster number                           42
Sampling weight                    0.790094
PSU                                      42
Stratum                                   2
Name: 311, dtype: object

Cardiometabolic Burden                 None
Socioeconomic Status                Richest
Depression                    0-4 (minimal)
Marital status            Currently married
Education                            Higher
Occupation                               No
Partner occupation                      NaN
Age                                   15-24
Division                         Chattogram
Residence                             Rural
Religion                              Islam
Children                        No children
Family size                       5 or more
Autonomy                        No autonomy
Abuse                                    No
Insurance                                No
Internet                              Never
Contraceptive                     No method
Abortion                                 No
Pregnant                       No or unsure
Menopause                                No
Sexual activity                      Active
Postpartum                               No
CASEID                           156   1  4
Cluster number                          156
Sampling weight                    1.616444
PSU                                     156
Stratum                                   4
Name: 1255, dtype: object

Cardiometabolic Burden           Two burden
Socioeconomic Status                Richest
Depression                    0-4 (minimal)
Marital status            Currently married
Education                      No education
Occupation                               No
Partner occupation                      NaN
Age                                   35-49
Division                              Dhaka
Residence                             Urban
Religion                              Islam
Children                          4 or more
Family size                       5 or more
Autonomy                        No autonomy
Abuse                                    No
Insurance                                No
Internet                              Never
Contraceptive                     No method
Abortion                                 No
Pregnant                       No or unsure
Menopause                                No
Sexual activity                  Not Active
Postpartum                               No
CASEID                           174 114  5
Cluster number                          174
Sampling weight                    1.176988
PSU                                     174
Stratum                                   5
Name: 1409, dtype: object

Cardiometabolic Burden           Two burden
Socioeconomic Status                Richest
Depression                       5-9 (mild)
Marital status            Currently married
Education                      No education
Occupation                               No
Partner occupation                      NaN
Age                                   35-49
Division                              Dhaka
Residence                             Rural
Religion                              Islam
Children                                  2
Family size                     Less than 5
Autonomy                        4 dicisions
Abuse                                   Yes
Insurance                                No
Internet                              Never
Contraceptive                     No method
Abortion                                 No
Pregnant                       No or unsure
Menopause                                No
Sexual activity                  Not Active
Postpartum                               No
CASEID                           224  43  1
Cluster number                          224
Sampling weight                    1.449553
PSU                                     224
Stratum                                   6
Name: 1751, dtype: object

Cardiometabolic Burden                 None
Socioeconomic Status                Richest
Depression                       5-9 (mild)
Marital status            Currently married
Education                            Higher
Occupation                               No
Partner occupation                      NaN
Age                                   15-24
Division                              Dhaka
Residence                             Rural
Religion                              Islam
Children                                  1
Family size                     Less than 5
Autonomy                        4 dicisions
Abuse                                    No
Insurance                                No
Internet                                Yes
Contraceptive                     No method
Abortion                                 No
Pregnant                       No or unsure
Menopause                                No
Sexual activity                  Not Active
Postpartum                               No
CASEID                           224  43  2
Cluster number                          224
Sampling weight                    1.449553
PSU                                     224
Stratum                                   6
Name: 1752, dtype: object

Cardiometabolic Burden                 None
Socioeconomic Status                Richest
Depression                    0-4 (minimal)
Marital status            Currently married
Education                            Higher
Occupation                               No
Partner occupation                      NaN
Age                                   25-34
Division                             Khulna
Residence                             Urban
Religion                              Islam
Children                        No children
Family size                     Less than 5
Autonomy                        4 dicisions
Abuse                                    No
Insurance                                No
Internet                                Yes
Contraceptive                 Modern method
Abortion                                 No
Pregnant                       No or unsure
Menopause                                No
Sexual activity                      Active
Postpartum                               No
CASEID                           293  65  3
Cluster number                          293
Sampling weight                    0.782882
PSU                                     293
Stratum                                   7
Name: 2245, dtype: object

Cardiometabolic Burden                 None
Socioeconomic Status                Poorest
Depression                       5-9 (mild)
Marital status            Currently married
Education                           Primary
Occupation                               No
Partner occupation                      NaN
Age                                   15-24
Division                           Rajshahi
Residence                             Rural
Religion                              Islam
Children                                  2
Family size                       5 or more
Autonomy                        3 decisions
Abuse                                   Yes
Insurance                                No
Internet                              Never
Contraceptive                 Modern method
Abortion                                 No
Pregnant                       No or unsure
Menopause                                No
Sexual activity                  Not Active
Postpartum                              Yes
CASEID                           517 116  3
Cluster number                          517
Sampling weight                     1.28781
PSU                                     517
Stratum                                  12
Name: 3926, dtype: object

Cardiometabolic Burden                 None
Socioeconomic Status                 Richer
Depression                    0-4 (minimal)
Marital status            Currently married
Education                           Primary
Occupation                               No
Partner occupation                      NaN
Age                                   15-24
Division                            Rangpur
Residence                             Urban
Religion                              Islam
Children                                  1
Family size                     Less than 5
Autonomy                        4 dicisions
Abuse                                    No
Insurance                                No
Internet                              Never
Contraceptive                     No method
Abortion                                 No
Pregnant                       No or unsure
Menopause                                No
Sexual activity                  Not Active
Postpartum                               No
CASEID                           528  93  3
Cluster number                          528
Sampling weight                    0.507989
PSU                                     528
Stratum                                  13
Name: 3999, dtype: object